[package]
name = "MySniffer"
version = "0.1.0"
authors = ["pmacciacchera <polmacra@outlook.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
